export const defaultTheme = {
  colors: {
    'base-white': '#FFFFFF',
    'base-text': '#ECEDEE',
    'base-background': '#0F0F0F',
    'base-button': '#E9FF1A',
    'base-card-biologia': '#CC4090',
    'base-card-artes': '#05A2C2',
    'base-card-geografia': '#C26719',
    'base-card-sociologia': '#9B19C2',
    'base-input': '#EDEDED',
    'base-note': '#0F0F0F',
  },
  textSizes: {
    'title-title-xl': '3rem',
    'title-title-l': '2rem',
    'title-title-m': '1.5rem',
    'title-title-s': '1.2rem',
    'title-title-xs': '1.125rem',
    'text-regular-l': '1.25rem',
    'text-bold-l': '1.25rem',
    'text-regular-m': '1rem',
    'text-bold-m': '1rem',
    'text-regular-s': '0.875rem',
    'text-bold-s': '0.75rem',
    'components-tag': '0.625rem',
    'components-button-g': '0.875rem',
    'components-button-s': '0.75rem',
  },
  fonts: {
    regular: 'Montserrat',
  },
}
